### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by hoodanav** [RohanAlexander/starter_folder#4]
Since the assignment seems to be still under works, here is some comments that may be useful what's given

Pdf
- Remove the "subtitle if needed line" it's rendered in your pdf
- Remember to finish the abstract, it is "First sentence,..." and so on right now 
- I think your fig tags in the writing sections are not rendering, they have a ? in it
- Add a Link to your repo on the bottom of the first page where it says "LINK"

General/Repo Related
- Overall code provided is clean and simple
- Sketches are included as needed
- Test Data script is not added
- Simulate Data has good detail and well-commented
- Make sure to update your README.md file to your specific assignment
-  Citations are incomplete, but remember to cite R (important!)
- Data tables, graphs are not added yet but remember to use kable and such tools to generate those, refer to course website
- Data Analysis writing is missing, ensure to include cross references throughout

**Comment by RohanAlexander** [comment]
@hoodanav please don't create the issue against the starter folder. But instead create it against the repo you are reviewing.
